csharp/OptimisedGolf/OptimisedGolf/Models/Game.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace OptimisedGolf.Models
{
    public class Game
    {
        private Hole[] holes;
        private List<Player>.Enumerator playerEnumerator;
        private Deck deck = new Deck(); // TODO: both of these have a list of cards... room for abstraction into a base class?
        private DiscardPile discardPile = new DiscardPile();
        //private int numberOfPlayers;

        [DisplayName("number of players")]
        public int NumberOfPlayers { get; set; }
        [DisplayName("full game?")]
        public bool FullGame { get; set; }
        //[DisplayName("players")]
        public List<Player> Players { get; private set; } = new List<Player>();

        // IDK HOW Y(OU ARE 
        public Game()
        {
            //idk man

        }

        public Game(int numberOfPlayers, bool fullGame) : this()//take total number of players, user is the only one making choices, others are defined randomly or something
        {
            this.NumberOfPlayers = numberOfPlayers;
            this.FullGame = fullGame;

            Console.WriteLine($"Starting new game with {(fullGame ? 9 : 18)} holes.");

            this.holes = new Hole[9];


            this.Players.AddRange(new PlayerFactory().CreatePlayers(numberOfPlayers));

            Console.WriteLine("Players:");
            this.Players.ForEach(a => Console.WriteLine(a.Name));

            this.holes = fullGame ? new Hole[18] : new Hole[9];
            //fullGame == true ? this.holes = new Hole[18] : this.holes = new Hole[9];

            this.playerEnumerator = this.Players.GetEnumerator();

            this.deck.Shuffle();
        }

            // a hole
//            for (int i = 0; i < this.holes.Length; i++)
//            {
//                Console.WriteLine($"Starting Hole #{i + 1}...");
//                Console.WriteLine();
                
//                //prompt for par
//                int PLACEHOLDEPAR = 3;
//                this.holes[i] = new Hole(PLACEHOLDEPAR);

//                // in reality the dealer should be "doing" this
//                for (int j = 0; j < PLACEHOLDEPAR; j++)
//                {
//                    foreach (Player player in this.Players)
//                    {
//                        if (this.deck.HasNext == false)
//                        {
//                            this.shuffleDiscardPileIntoDeck();
//                        }

//                        player.Hand.Add(this.deck.DealOne());
//                    }
//                }

//                foreach(Player player in this.Players)
//                {
//                    Console.WriteLine($"Dealt player {player.Name} cards:");

//                    for (int j = 0; j < PLACEHOLDEPAR; j++)
//                    {
//                        Console.WriteLine(player.Hand[j].Suite + " " + player.Hand[j].Rank);
//                    }

//                    Console.WriteLine();
//                }

//                // players get to look at (know) some cards
//                // prompt for cardsToPeek for each player
//                int[] CARDSTOPEEK = new int[1]; // because of the hardcoded par
//                CARDSTOPEEK[0] = 1; // hardcoded middle card
//                this.Players.ForEach(a => a.Peek(CARDSTOPEEK));

//                Console.WriteLine();

//                this.playerEnumerator.MoveNext(); // player to left of dealer goes first

//                //player chooses 
//                ChoiceOne firstChoice = ChoiceOne.RevealCard;
//                this.Players.ForEach(a => a.ChooseFirst(firstChoice));
//                ChoiceTwo choiceTwo = ChoiceTwo.RevealKnown;
//                this.Players.ForEach(a => a.ChooseSecond(choiceTwo));

//                //etc.

//                // score
//                //            Once a card is revealed, it is permanenet and may not be replaced.

////The hole continues until all of each player's cards are revealed.

////At the end of the hole, the score for each player is calculated, all cards are collected into the deck, and the new dealer shuffles and deals the next hole.


            //    // new hole
            //    this.shuffleAllCardsIntoDeck();

            //    this.playerEnumerator.MoveNext();
            //}
//            Each hole, one of the players acts as a dealer.The dealer's only job is to deal the cards at the beginning of the hole. The dealer for the next hole is the person to the left of the current dealer.

//At the start of each hole, the dealer deals each player / par / cards.

//During each hole, each player may look at a certain number of cards they've been dealt, depending on the hole's par. When a player looks at the cards, the cards become known to that player.

//For a par 5, players may look at two of their cards.

//For a par 4, players may look at two of their cards.

//For a par 3, players may look at one of their cards.

//In real life, a player may only look at his / her cards once per hole. If the player forgets his / her cards, he / she can use a mulligan(only one per player per game) to look at the cards again.

//The player to the left of the dealer goes first. During the first round, the first player must:

//            1.Reveal a card from the top of the deck, placing it in the discard pile, or

//       not reveal a card


//2.Reveal one of their known cards, keeping it in their possession, or


       // reveal one of their unrevealed cards, keeping it in their possession, or


       // replace one of their known cards with the card at the top of the discard pile(if one exists), or

       //replace one of their unrevealed cards with the card at the top of the discard pile(if one exists)

//            Once a card is revealed, it is permanenet and may not be replaced.

//The hole continues until all of each player's cards are revealed.

//At the end of the hole, the score for each player is calculated, all cards are collected into the deck, and the new dealer shuffles and deals the next hole.

        }

        private void shuffleDiscardPileIntoDeck()
        {
            this.deck.AddCards(this.discardPile.TakeAll());
            this.deck.Shuffle();
        }

        private void shuffleAllCardsIntoDeck()
        {
            this.Players.ForEach(p =>
            {
                this.deck.AddCards(p.Hand);
                p.Hand.Clear();
            });

            this.shuffleDiscardPileIntoDeck();
        }
    }
}

csharp/OptimisedGolf/OptimisedGolf/Models/Hole.cs
using System;
using System.ComponentModel;

namespace OptimisedGolf.Models
{
    public class Hole
    {
        [DisplayName("par for this hole")]
        public int Par { get; set; }

        //public Player Dealer { get; set; }

        public Hole()
        {
            
        }

        public Hole(int par)//, Player dealer)
        {
            this.Par = par;
        }
    }
}

csharp/OptimisedGolf/OptimisedGolf/Controllers/HoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OptimisedGolf.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace OptimisedGolf.Controllers
{
    public class HoleController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult StartNewHole(int par)
        {
            var viewmodel = new Hole(par);

            return View(viewmodel);
        }
    }
}

csharp/OptimisedGolf/OptimisedGolf/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OptimisedGolf.Models;

namespace OptimisedGolf.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult Game(Game game)
        {
            //var viewmodel = new Game(numberOfPlayers, isFullGame);
            var viewmodel = new Game(game.NumberOfPlayers, game.FullGame);

            return View(viewmodel);
        }
    }
}

csharp/OptimisedGolf/OptimisedGolf/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

csharp/OptimisedGolf/OptimisedGolf/Views/Home/Game.cshtml
@{
    ViewData["Title"] = "New game";
}
@model Game
<h1>@ViewData["Title"]</h1>
<p>This is a new game with @Model.NumberOfPlayers players and @Model.FullGame</p>
<h2>Players</h2>
@foreach (Player player in Model.Players)
{
    <div>
        @player.Name
        <div>
                @foreach (Card card in player.Hand)
                {
                    <div>
                        @card.PrettyPrintWithState()
                    </div>
                }
            </div>
        <hr />
    </div>
}


@*<form asp-action="StartNewHole" asp-controller="Hole">
        <p>
            <label asp-for="Par"></label>
            <input type="number" id="Par" name="Par" value="" placeholder="par for this hole" />
        </p>
        <input type="submit" name="start new hole" />
    </form>*@

csharp/OptimisedGolf/OptimisedGolf/Views/Home/Hole.cshtml
@{
    ViewData["Title"] = "New hole";
}
@model Hole
<h2>@ViewData["Title"]</h2>
<form asp-action="StartNewHole" asp-controller="Hole">
    <p>
        <label asp-for="Par"></label>
        <input type="number" id="Par" name="Par" value="" placeholder="par for this hole" />
    </p>
    <input type="submit" name="start new hole" />
</form>

csharp/OptimisedGolf/OptimisedGolf/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Golf (the card game) Home";
}
@model Game
<div class="row">
    <div class="col-md-3">
        <h2>Start a new round</h2>
        <form asp-action="Game" asp-controller="Home">
            <p>
                <label asp-for="NumberOfPlayers"></label>
                <input asp-for="NumberOfPlayers" placeholder="players" type="number"/>
            </p>
            <p>
                <label asp-for="FullGame"></label>
                <input asp-for="FullGame" placeholder="full game?" type="checkbox"/>
            </p>

            <input type="submit" name="start new game"/>
        </form>

        <!--<p>How many total players?</p>
        <input type="number" name="numberOfPlayers" />
        <p>Is this a full game?</p>
        <input type="checkbox" name="fullGame" />
        <a asp-area="" asp-controller="Home" asp-action="StartNewGameIPlay">StartNewGameIPlay</a>-->
    </div>
    <!--<input type="button" name="start new game"/>-->
</div>